project_name: k6x
version: 2
before:
  hooks:
    - go mod tidy
dist: build/dist
builds:
  - env:
      - CGO_ENABLED=0
    goos: ["darwin", "linux", "windows"]
    goarch: ["amd64", "arm64"]
    ldflags:
      - "-s -w -X main.version={{.Version}} -X main.appname={{.ProjectName}}"
source:
  enabled: true
  name_template: "{{ .ProjectName }}_{{ .Version }}_source"

archives:
  - id: bundle
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: "{{ .ProjectName }}_{{ .Version }}_checksums.txt"

snapshot:
  name_template: "{{ incpatch .Version }}-next+{{.ShortCommit}}{{if .IsGitDirty}}.dirty{{else}}{{end}}"

changelog:
  sort: asc
  abbrev: -1
  filters:
    exclude:
      - "^chore:"
      - "^docs:"
      - "^test:"

git:
  ignore_tags:
    - "nightly"
    - "before-grafana"

dockers:
  - id: amd64
    dockerfile: Dockerfile.goreleaser
    use: buildx
    image_templates:
      - "grafana/{{ .ProjectName }}:{{ .Tag }}-amd64"
      - "grafana/{{ .ProjectName }}:v{{ .Major }}-amd64"
      - "grafana/{{ .ProjectName }}:v{{ .Major }}.{{ .Minor }}-amd64"
      - "grafana/{{ .ProjectName }}:latest-amd64"

    build_flag_templates:
      - "--platform=linux/amd64"
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.licenses=AGPL-3.0-only"
  - id: arm64
    dockerfile: Dockerfile.goreleaser
    use: buildx
    image_templates:
      - "grafana/{{ .ProjectName }}:{{ .Tag }}-arm64"
      - "grafana/{{ .ProjectName }}:v{{ .Major }}-arm64"
      - "grafana/{{ .ProjectName }}:v{{ .Major }}.{{ .Minor }}-arm64"
      - "grafana/{{ .ProjectName }}:latest-arm64"

    build_flag_templates:
      - "--platform=linux/arm64"
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.licenses=AGPL-3.0-only"

docker_manifests:
  - id: tag
    name_template: "grafana/{{ .ProjectName }}:{{ .Tag }}"
    image_templates:
      - "grafana/{{ .ProjectName }}:{{ .Tag }}-amd64"
      - "grafana/{{ .ProjectName }}:{{ .Tag }}-arm64"
  - id: major
    name_template: "grafana/{{ .ProjectName }}:v{{ .Major }}"
    image_templates:
      - "grafana/{{ .ProjectName }}:v{{ .Major }}-amd64"
      - "grafana/{{ .ProjectName }}:v{{ .Major }}-arm64"
  - id: major-minor
    name_template: "grafana/{{ .ProjectName }}:v{{ .Major }}.{{ .Minor }}"
    image_templates:
      - "grafana/{{ .ProjectName }}:v{{ .Major }}.{{ .Minor }}-amd64"
      - "grafana/{{ .ProjectName }}:v{{ .Major }}.{{ .Minor }}-arm64"
  - id: latest
    name_template: "grafana/{{ .ProjectName }}:latest"
    image_templates:
      - "grafana/{{ .ProjectName }}:latest-amd64"
      - "grafana/{{ .ProjectName }}:latest-arm64"
